### ISSUE TITLE
BUDDY_PARSE_APP_ID

### ISSUE THREAD

**Issue by fahedyasin** [BuddyPlatform/parse-on-buddy-cli#6]
How do I set these keys in my system environment variables, but does not work.
Whenever I run following command
parse-on-buddy -v
I get following messsage
Required environment variables: BUDDY_PARSE_APP_ID, BUDDY_PARSE_MASTER_KEY

**Comment by craigpatten** [comment]
Hi, thanks for getting in touch. Are you on Windows or Linux/BSD/...?

**Comment by bradserbuddy** [comment]
Hi @fahedprince, please see our documentation at https://buddy.com/parse/cloud-code-web-hosting/#environment for specific instructions on setting the environment variables. Thanks!
